- block:
  - name: Ensure admin users exist with sudo
    ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: wheel
      append: yes
      state: present
    loop: "{{ admin_users }}"

  - name: Set authorized_keys for admin users
    ansible.posix.authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', 'files/ssh/' + item + '_authorized_keys') }}"
    loop: "{{ admin_users }}"

  - name: Allow passwordless sudo for admin users
    ansible.builtin.copy:
      dest: "/etc/sudoers.d/{{ item }}"
      owner: root
      group: root
      mode: '0440'
      content: "{{ item }} ALL=(ALL) NOPASSWD:ALL\n"
      validate: "visudo -cf %s"
    loop: "{{ admin_users }}"
  when: setup_admin_users == true
